### ISSUE TITLE
Simple Array Manipulations

### ISSUE THREAD

**Issue by lorena57** [learn-co-curriculum/programming-univbasics-4-array-simple-array-manipulations#4]
The instructions for the def for pop_with_args is not consistent with all the other instructions. The  pop_with_args argument for array is not highlighted as well as the .pop method.
![Screen Shot 2019-07-11 at 4 31 55 PM](https://user-images.githubusercontent.com/34522096/61092056-7e244080-a3f9-11e9-8ad3-8fd5cf548b92.png)

**Comment by maxwellbenton** [comment]
Hi @lorena57,

Thanks for spotting this and providing feedback. The formatting has been fixed in the `pop_with_args` section to align with the other instructions.

Thank you for contributing to a Learn lesson!
